"""initial schema — squashed baseline

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-07-20

Supersedes the incremental chain 0001_create_aoi_table … 0021_settings_change,
squashed after the stack-omnibus merge (#141) while no deployed instance
existed: a database stamped with any pre-squash revision cannot upgrade across
this boundary — redeploy from scratch instead. The pre-squash data backfills
(0012 display versions, 0020 raster lineages / extraction markers) are
intentionally gone: from-scratch databases have nothing to backfill. Geometry
columns auto-create their GIST indexes via geoalchemy2, exactly as the
pre-squash migrations did.
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The datasets behind every observation.sensor value (carried from 0015).
_SENSOR_SEED = (
    ("HLSL30", "optical", "NASA/HLS/HLSL30/v002", '{"platform": "Landsat 8/9"}'),
    ("HLSS30", "optical", "NASA/HLS/HLSS30/v002", '{"platform": "Sentinel-2"}'),
    ("S1GRD", "radar", "COPERNICUS/S1_GRD", '{"mode": "IW", "polarisation": "VV"}'),
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "aoi",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_aoi")),
        sa.UniqueConstraint("name", name=op.f("uq_aoi_name")),
    )
    op.create_table(
        "context_layer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("source_file", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('concession', 'protected_area', 'road', 'river', 'settlement', 'mill', 'port', 'other')",  # noqa: E501 - autogenerated name
            name=op.f("ck_context_layer_kind"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_layer")),
        sa.UniqueConstraint("name", name="uq_context_layer_name"),
    )
    op.create_table(
        "raster_lineage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raster_lineage")),
        sa.UniqueConstraint("name", "version", name="uq_raster_lineage_name_version"),
    )
    op.create_table(
        "sensor_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("collection", sa.String(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("kind IN ('optical', 'radar')", name=op.f("ck_sensor_source_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensor_source")),
        sa.UniqueConstraint("name", name="uq_sensor_source_name"),
    )
    op.create_table(
        "settings_change",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("old_value", sa.String(), nullable=True),
        sa.Column("new_value", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings_change")),
    )
    op.create_table(
        "context_feature",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("context_layer_id", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry", nullable=False
            ),
            nullable=False,
        ),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["context_layer_id"],
            ["context_layer.id"],
            name=op.f("fk_context_feature_context_layer_id_context_layer"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_context_feature")),
    )
    op.create_index(
        "ix_context_feature_context_layer_id", "context_feature", ["context_layer_id"], unique=False
    )
    op.create_table(
        "methodology_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("display_version", sa.String(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raster_lineage_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["raster_lineage_id"],
            ["raster_lineage.id"],
            name="fk_methodology_version_raster_lineage",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_methodology_version")),
        sa.UniqueConstraint("name", "display_version", name="uq_methodology_version_name_display"),
        sa.UniqueConstraint("name", "version", name="uq_methodology_version_name_version"),
    )
    op.create_table(
        "observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aoi_id", sa.Integer(), nullable=False),
        sa.Column("sensor", sa.String(), nullable=False),
        sa.Column("acquired_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_scene_id", sa.String(), nullable=False),
        sa.Column("cloud_cover_percent", sa.Float(), nullable=True),
        sa.Column("orbit_direction", sa.String(), nullable=True),
        sa.Column("relative_orbit", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["aoi_id"], ["aoi.id"], name=op.f("fk_observation_aoi_id_aoi")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation")),
        sa.UniqueConstraint(
            "aoi_id", "source_scene_id", name="uq_observation_aoi_id_source_scene_id"
        ),
    )
    op.create_index(
        "ix_observation_aoi_id_acquired_at", "observation", ["aoi_id", "acquired_at"], unique=False
    )
    op.create_table(
        "change_raster",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("raster_lineage_id", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.String(), nullable=False),
        sa.Column("cog_path", sa.String(), nullable=False),
        sa.Column("baseline_window", sa.Integer(), nullable=False),
        sa.Column("valid_pixel_fraction", sa.Float(), nullable=True),
        sa.Column(
            "baseline_source_scene_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
            name=op.f("fk_change_raster_observation_id_observation"),
        ),
        sa.ForeignKeyConstraint(
            ["raster_lineage_id"],
            ["raster_lineage.id"],
            name=op.f("fk_change_raster_raster_lineage_id_raster_lineage"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_raster")),
        sa.UniqueConstraint(
            "observation_id", "change_type", "raster_lineage_id", name="uq_change_raster_identity"
        ),
    )
    op.create_table(
        "disturbance_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aoi_id", sa.Integer(), nullable=False),
        sa.Column("methodology_version_id", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("first_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["aoi_id"], ["aoi.id"], name=op.f("fk_disturbance_event_aoi_id_aoi")
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_version.id"],
            name="fk_disturbance_event_methodology",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disturbance_event")),
    )
    op.create_table(
        "index_raster",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("raster_lineage_id", sa.Integer(), nullable=False),
        sa.Column("index_type", sa.String(), nullable=False),
        sa.Column("cog_path", sa.String(), nullable=False),
        sa.Column("valid_pixel_fraction", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
            name=op.f("fk_index_raster_observation_id_observation"),
        ),
        sa.ForeignKeyConstraint(
            ["raster_lineage_id"],
            ["raster_lineage.id"],
            name=op.f("fk_index_raster_raster_lineage_id_raster_lineage"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_raster")),
        sa.UniqueConstraint(
            "observation_id", "index_type", "raster_lineage_id", name="uq_index_raster_identity"
        ),
    )
    op.create_table(
        "pipeline_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aoi_id", sa.Integer(), nullable=False),
        sa.Column("methodology_version_id", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("since", sa.Date(), nullable=False),
        sa.Column("until", sa.Date(), nullable=False),
        sa.Column("aoi_geometry_hash", sa.String(), nullable=True),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["aoi_id"], ["aoi.id"], name=op.f("fk_pipeline_run_aoi_id_aoi")),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_version.id"],
            name="fk_pipeline_run_methodology",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_run")),
    )
    op.create_index(
        "ix_pipeline_run_aoi_id_started_at", "pipeline_run", ["aoi_id", "started_at"], unique=False
    )
    op.create_table(
        "quality_mask",
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("valid_pixel_fraction", sa.Float(), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observation.id"],
            name=op.f("fk_quality_mask_observation_id_observation"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_quality_mask")),
    )
    op.create_table(
        "candidate_extraction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("change_raster_id", sa.Integer(), nullable=False),
        sa.Column("methodology_version_id", sa.Integer(), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_raster_id"],
            ["change_raster.id"],
            name=op.f("fk_candidate_extraction_change_raster_id_change_raster"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_version.id"],
            name="fk_candidate_extraction_methodology",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_extraction")),
        sa.UniqueConstraint(
            "change_raster_id", "methodology_version_id", name="uq_candidate_extraction_identity"
        ),
    )
    op.create_table(
        "change_raster_source",
        sa.Column("change_raster_id", sa.Integer(), nullable=False),
        sa.Column("index_raster_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["change_raster_id"],
            ["change_raster.id"],
            name=op.f("fk_change_raster_source_change_raster_id_change_raster"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["index_raster_id"],
            ["index_raster.id"],
            name=op.f("fk_change_raster_source_index_raster_id_index_raster"),
        ),
        sa.PrimaryKeyConstraint(
            "change_raster_id", "index_raster_id", name=op.f("pk_change_raster_source")
        ),
    )
    op.create_table(
        "confidence_assessment",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("pipeline_run_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.String(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rule_version", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "level IN ('low', 'medium', 'high')", name=op.f("ck_confidence_assessment_level")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["disturbance_event.id"],
            name=op.f("fk_confidence_assessment_event_id_disturbance_event"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"], ["pipeline_run.id"], name="fk_confidence_assessment_run"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confidence_assessment")),
    )
    op.create_index(
        "ix_confidence_assessment_event_id", "confidence_assessment", ["event_id"], unique=False
    )
    op.create_table(
        "disturbance_candidate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("change_raster_id", sa.Integer(), nullable=False),
        sa.Column("methodology_version_id", sa.Integer(), nullable=False),
        sa.Column(
            "geometry",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column("delta_mean", sa.Float(), nullable=True),
        sa.Column("delta_min", sa.Float(), nullable=True),
        sa.Column("valid_pixel_fraction", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_raster_id"],
            ["change_raster.id"],
            name=op.f("fk_disturbance_candidate_change_raster_id_change_raster"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["methodology_version_id"],
            ["methodology_version.id"],
            name="fk_disturbance_candidate_methodology",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_disturbance_candidate")),
    )
    op.create_index(
        "ix_disturbance_candidate_change_raster_id",
        "disturbance_candidate",
        ["change_raster_id"],
        unique=False,
    )
    op.create_table(
        "event_context",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("context_feature_id", sa.Integer(), nullable=False),
        sa.Column("relation", sa.String(), nullable=False),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "relation IN ('contains', 'intersects', 'nearby')",
            name=op.f("ck_event_context_relation"),
        ),
        sa.ForeignKeyConstraint(
            ["context_feature_id"],
            ["context_feature.id"],
            name=op.f("fk_event_context_context_feature_id_context_feature"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["disturbance_event.id"],
            name=op.f("fk_event_context_event_id_disturbance_event"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_context")),
    )
    op.create_index("ix_event_context_event_id", "event_context", ["event_id"], unique=False)
    op.create_table(
        "manual_review",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("opinion", sa.String(), nullable=False),
        sa.Column("notes", sa.String(), nullable=True),
        sa.Column("reviewer", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "opinion IN ('confirmed', 'false_positive', 'uncertain', 'resolved')",
            name=op.f("ck_manual_review_opinion"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["disturbance_event.id"],
            name=op.f("fk_manual_review_event_id_disturbance_event"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_review")),
    )
    op.create_index("ix_manual_review_event_id", "manual_review", ["event_id"], unique=False)
    op.create_table(
        "pipeline_run_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("batch_index", sa.Integer(), nullable=True),
        sa.Column("batch_total", sa.Integer(), nullable=True),
        sa.Column("exports", sa.Integer(), nullable=True),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_run.id"],
            name=op.f("fk_pipeline_run_event_run_id_pipeline_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_run_event")),
    )
    op.create_index("ix_pipeline_run_event_run_id", "pipeline_run_event", ["run_id"], unique=False)
    op.create_table(
        "event_observation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("disturbance_candidate_id", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("area_m2", sa.Float(), nullable=False),
        sa.Column("growth_m2", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["disturbance_candidate_id"],
            ["disturbance_candidate.id"],
            name=op.f("fk_event_observation_disturbance_candidate_id_disturbance_candidate"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["disturbance_event.id"],
            name=op.f("fk_event_observation_event_id_disturbance_event"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_observation")),
        sa.UniqueConstraint(
            "disturbance_candidate_id", name="uq_event_observation_disturbance_candidate_id"
        ),
    )
    op.create_index(
        "ix_event_observation_event_id", "event_observation", ["event_id"], unique=False
    )
    bind = op.get_bind()
    for name, kind, collection, details in _SENSOR_SEED:
        bind.execute(
            sa.text(
                "INSERT INTO sensor_source (name, kind, collection, details) "
                "VALUES (:n, :k, :c, CAST(:d AS jsonb))"
            ),
            {"n": name, "k": kind, "c": collection, "d": details},
        )


def downgrade() -> None:
    op.drop_index("ix_event_observation_event_id", table_name="event_observation")
    op.drop_table("event_observation")
    op.drop_index("ix_pipeline_run_event_run_id", table_name="pipeline_run_event")
    op.drop_table("pipeline_run_event")
    op.drop_index("ix_manual_review_event_id", table_name="manual_review")
    op.drop_table("manual_review")
    op.drop_index("ix_event_context_event_id", table_name="event_context")
    op.drop_table("event_context")
    op.drop_index("ix_disturbance_candidate_change_raster_id", table_name="disturbance_candidate")
    op.drop_table("disturbance_candidate")
    op.drop_index("ix_confidence_assessment_event_id", table_name="confidence_assessment")
    op.drop_table("confidence_assessment")
    op.drop_table("change_raster_source")
    op.drop_table("candidate_extraction")
    op.drop_table("quality_mask")
    op.drop_index("ix_pipeline_run_aoi_id_started_at", table_name="pipeline_run")
    op.drop_table("pipeline_run")
    op.drop_table("index_raster")
    op.drop_table("disturbance_event")
    op.drop_table("change_raster")
    op.drop_index("ix_observation_aoi_id_acquired_at", table_name="observation")
    op.drop_table("observation")
    op.drop_table("methodology_version")
    op.drop_index("ix_context_feature_context_layer_id", table_name="context_feature")
    op.drop_table("context_feature")
    op.drop_table("settings_change")
    op.drop_table("sensor_source")
    op.drop_table("raster_lineage")
    op.drop_table("context_layer")
    op.drop_table("aoi")
