#!/usr/bin/env bash
# On-VM provisioning for Open Forest Sentinel. Run this ON the Compute Engine VM
# (Debian 12) — either manually over SSH, or automatically via the startup-script
# wrapper (scripts/vm_startup.sh). Installs Docker + uv, clones the repo, starts
# PostgreSQL + PostGIS, applies migrations, and installs the systemd units for
# the dashboard and the scheduled pipeline. Idempotent.
#
# No credentials file is needed: the VM's attached service account (see
# provision_vm.sh) provides Application Default Credentials via the metadata
# server. App settings come from the committed config/instance.env — this script
# REGENERATES ${APP_DIR}/.env on every run, so make persistent changes in
# config/instance.env (and re-run this script), not in .env.
#
# Configure via environment variables:
#   REPO_URL     git URL to clone   (default: https://github.com/jackrsteiner/open-forest-sentinel.git)
#   REPO_REF     branch / tag / sha (default: main)
#   APP_DIR      checkout location  (default: $HOME/open-forest-sentinel)
#   RUN_INITIAL  set to 1 to trigger a pipeline run at the end (default: 0)
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/jackrsteiner/open-forest-sentinel.git}"
REPO_REF="${REPO_REF:-main}"
APP_DIR="${APP_DIR:-$HOME/open-forest-sentinel}"
RUN_INITIAL="${RUN_INITIAL:-0}"

echo "==> Installing system packages (git, Docker, uv)"
sudo apt-get update -y
sudo apt-get install -y git ca-certificates curl
if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "$USER" || true
fi
if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="${HOME}/.local/bin:${PATH}"

echo "==> Cloning ${REPO_URL} @ ${REPO_REF} into ${APP_DIR}"
if [ ! -d "${APP_DIR}/.git" ]; then
    git clone "${REPO_URL}" "${APP_DIR}"
fi
cd "${APP_DIR}"
git fetch origin "${REPO_REF}"
git checkout "${REPO_REF}"
# Mirror the remote exactly (the checkout is a deploy artifact, never a place
# for local commits): a harvested AOI upload arrives as a tracked file even
# though an identical untracked copy sits in config/aois/ — a plain pull
# refuses that overwrite; reset adopts it, and untracked files absent from the
# incoming tree (not-yet-harvested uploads) survive. Fall back to a pull when
# REPO_REF is a tag/sha with no origin/ branch to reset to.
git reset --hard "origin/${REPO_REF}" 2>/dev/null \
    || git pull --ff-only origin "${REPO_REF}" || true

echo "==> Installing the canonical COG store at /data/cogs"
sudo mkdir -p /data/cogs
sudo chown -R "$USER" /data

# Read the committed instance config (PROJECT_ID, STAGING_BUCKET, ...). The
# metadata server supplies PROJECT_ID when it isn't set there.
INSTANCE_ENV="${APP_DIR}/config/instance.env"
if [ -f "${INSTANCE_ENV}" ]; then
    # shellcheck disable=SC1090
    . "${INSTANCE_ENV}"
fi
# Dashboard settings edits override instance.env for the values rendered below
# (schedules, timeout). Safe to source: the write path only emits space-free,
# shell-inert values (bead 7.5).
OVERRIDES_ENV="${APP_DIR}/config/overrides.env"
if [ -f "${OVERRIDES_ENV}" ]; then
    # shellcheck disable=SC1090
    . "${OVERRIDES_ENV}"
fi
if [ -z "${PROJECT_ID:-}" ]; then
    PROJECT_ID="$(curl -sf -H 'Metadata-Flavor: Google' \
        http://metadata.google.internal/computeMetadata/v1/project/project-id 2>/dev/null || true)"
fi
DASHBOARD_PORT="${DASHBOARD_PORT:-8000}"
PIPELINE_TIMEOUT="${PIPELINE_TIMEOUT:-20h}"
# Timer schedules (bead 7.5): a time of day (renders as daily) or a systemd
# shorthand (hourly/daily/weekly). Space-free by construction — see above.
PIPELINE_SCHEDULE="${PIPELINE_SCHEDULE:-03:00:00}"
PRUNE_SCHEDULE="${PRUNE_SCHEDULE:-02:30:00}"
# Image mode (#96): blank (the default) builds from source with uv; a
# published image reference (e.g. ghcr.io/<owner>/open-forest-sentinel:<sha>)
# runs the pipeline/dashboard/prune from that container instead.
APP_IMAGE="${APP_IMAGE:-}"

echo "==> Writing ${APP_DIR}/.env (generated — persistent edits go in config/instance.env)"
{
    echo "# GENERATED by scripts/vm_setup.sh — edits here are lost on re-run."
    echo "# Change config/instance.env instead, then re-run scripts/vm_setup.sh."
    # ADC must come from the metadata server (attached service account); a stale
    # GOOGLE_APPLICATION_CREDENTIALS pointing at a missing key file breaks it.
    grep -v '^GOOGLE_APPLICATION_CREDENTIALS=' "${APP_DIR}/.env.example"
    if [ -f "${INSTANCE_ENV}" ]; then
        echo ""
        echo "# --- from config/instance.env ---"
        cat "${INSTANCE_ENV}"
    fi
    # Dashboard settings edits (Slice 7): appended AFTER instance.env so the
    # latest edit wins, but BEFORE the computed + world-open lines below, which
    # must always win over anything this file could carry.
    if [ -f "${APP_DIR}/config/overrides.env" ]; then
        echo ""
        echo "# --- from config/overrides.env (dashboard settings edits) ---"
        cat "${APP_DIR}/config/overrides.env"
    fi
    echo ""
    echo "# --- computed by vm_setup.sh (last assignment wins) ---"
    echo "FOREST_SENTINEL_COG_ROOT=/data/cogs"
    if [ -n "${PROJECT_ID:-}" ]; then
        echo "FOREST_SENTINEL_GEE_PROJECT=${PROJECT_ID}"
        echo "FOREST_SENTINEL_GCS_STAGING_BUCKET=${STAGING_BUCKET:-${PROJECT_ID}-ofs-staging}"
    fi
    if [ -f "${APP_DIR}/config/aoi.geojson" ]; then
        echo "AOI_PATH=config/aoi.geojson"
    fi
    # A world-open dashboard must stay read-only: disable the AOI-upload,
    # run-now/stop, review, context-upload, and settings-edit endpoints
    # whenever the firewall exposes the port publicly.
    if [ "${OPEN_DASHBOARD:-0}" = "1" ]; then
        echo "FOREST_SENTINEL_AOI_UPLOADS=0"
        echo "FOREST_SENTINEL_PIPELINE_TRIGGER=0"
        echo "FOREST_SENTINEL_REVIEWS=0"
        echo "FOREST_SENTINEL_CONTEXT_UPLOADS=0"
        echo "FOREST_SENTINEL_SETTINGS_EDIT=0"
    fi
} >"${APP_DIR}/.env"

# Committed seeds and dashboard uploads both live here (run_pipeline.sh runs
# every *.geojson in it, in addition to AOI_PATH).
mkdir -p "${APP_DIR}/config/aois"
if [ -z "${PROJECT_ID:-}" ]; then
    echo "warning: PROJECT_ID is not set in config/instance.env and the metadata" >&2
    echo "         server is unavailable — edit ${APP_DIR}/.env before running the pipeline." >&2
fi

echo "==> Starting PostgreSQL + PostGIS and applying migrations"
if [ -z "${APP_IMAGE}" ]; then
    uv sync
fi
# sudo: the docker-group membership granted above does not apply to the current
# login session, so plain `docker` would fail on the first (fresh-VM) run.
sudo docker compose up -d
for _ in $(seq 1 30); do
    sudo docker compose exec -T db pg_isready -U forest_sentinel >/dev/null 2>&1 && break
    sleep 2
done
set -a; . "${APP_DIR}/.env"; set +a
if [ -n "${APP_IMAGE}" ]; then
    echo "==> Image mode: pulling ${APP_IMAGE} (no source build on the VM)"
    sudo docker pull "${APP_IMAGE}"
    sudo docker run --rm --network host --env-file "${APP_DIR}/.env" \
        "${APP_IMAGE}" alembic upgrade head
else
    uv run alembic upgrade head
fi

echo "==> Installing systemd units"
sed "s#@APP_DIR@#${APP_DIR}#g; s#@USER@#${USER}#g" \
    scripts/systemd/forest-sentinel-dashboard.service \
    | sudo tee /etc/systemd/system/forest-sentinel-dashboard.service >/dev/null
sed "s#@APP_DIR@#${APP_DIR}#g; s#@USER@#${USER}#g; s#@PIPELINE_TIMEOUT@#${PIPELINE_TIMEOUT}#g" \
    scripts/systemd/forest-sentinel-pipeline.service \
    | sudo tee /etc/systemd/system/forest-sentinel-pipeline.service >/dev/null
sed "s#@PIPELINE_SCHEDULE@#${PIPELINE_SCHEDULE}#g" \
    scripts/systemd/forest-sentinel-pipeline.timer \
    | sudo tee /etc/systemd/system/forest-sentinel-pipeline.timer >/dev/null
sed "s#@APP_DIR@#${APP_DIR}#g; s#@USER@#${USER}#g" \
    scripts/systemd/forest-sentinel-prune.service \
    | sudo tee /etc/systemd/system/forest-sentinel-prune.service >/dev/null
sed "s#@PRUNE_SCHEDULE@#${PRUNE_SCHEDULE}#g" \
    scripts/systemd/forest-sentinel-prune.timer \
    | sudo tee /etc/systemd/system/forest-sentinel-prune.timer >/dev/null
sudo systemctl daemon-reload
sudo systemctl enable --now forest-sentinel-dashboard.service
sudo systemctl enable --now forest-sentinel-pipeline.timer
sudo systemctl enable --now forest-sentinel-prune.timer
# Pick up the regenerated .env on re-runs (enable --now is a no-op when running).
sudo systemctl restart forest-sentinel-dashboard.service

if [ "${RUN_INITIAL}" = "1" ]; then
    echo "==> Triggering the initial pipeline run (async; watch journalctl)"
    sudo systemctl start forest-sentinel-pipeline.service --no-block
fi

cat <<EOF

On-VM setup complete.

  Settings live in config/instance.env (committed) — after changing it, re-run
  this script to regenerate .env and restart the dashboard.

  Dashboard:        systemctl status forest-sentinel-dashboard
  Scheduled run:    systemctl status forest-sentinel-pipeline.timer
  Trigger a run now: sudo systemctl start forest-sentinel-pipeline.service
  Logs:             journalctl -u forest-sentinel-pipeline -f
EOF
