#!/usr/bin/env bash
# On-VM provisioning for Open Forest Sentinel. Run this ON the Compute Engine VM
# (Debian 12) — either manually over SSH, or automatically via the startup-script
# wrapper (scripts/vm_startup.sh). Installs Docker + uv, clones the repo, starts
# PostgreSQL + PostGIS, applies migrations, and installs the systemd units for
# the dashboard and the scheduled pipeline. Idempotent.
#
# No credentials file is needed: the VM's attached service account (see
# provision_vm.sh) provides Application Default Credentials via the metadata
# server. App settings come from the committed config/instance.env — this script
# REGENERATES ${APP_DIR}/.env on every run, so make persistent changes in
# config/instance.env (and re-run this script), not in .env.
#
# Configure via environment variables:
#   REPO_URL     git URL to clone   (default: https://github.com/jackrsteiner/open-forest-sentinel.git)
#   REPO_REF     branch / tag / sha (default: main)
#   APP_DIR      checkout location  (default: $HOME/open-forest-sentinel)
#   RUN_INITIAL  set to 1 to trigger a pipeline run at the end (default: 0)
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/jackrsteiner/open-forest-sentinel.git}"
REPO_REF="${REPO_REF:-main}"
APP_DIR="${APP_DIR:-$HOME/open-forest-sentinel}"
RUN_INITIAL="${RUN_INITIAL:-0}"

echo "==> Installing system packages (git, Docker, uv)"
sudo apt-get update -y
sudo apt-get install -y git ca-certificates curl
if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sudo sh
    sudo usermod -aG docker "$USER" || true
fi
if ! command -v uv >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
fi
export PATH="${HOME}/.local/bin:${PATH}"

echo "==> Cloning ${REPO_URL} @ ${REPO_REF} into ${APP_DIR}"
if [ ! -d "${APP_DIR}/.git" ]; then
    git clone "${REPO_URL}" "${APP_DIR}"
fi
cd "${APP_DIR}"
git fetch origin "${REPO_REF}"
git checkout "${REPO_REF}"
git pull --ff-only origin "${REPO_REF}" || true

echo "==> Installing the canonical COG store at /data/cogs"
sudo mkdir -p /data/cogs
sudo chown -R "$USER" /data

# Read the committed instance config (PROJECT_ID, STAGING_BUCKET, ...). The
# metadata server supplies PROJECT_ID when it isn't set there.
INSTANCE_ENV="${APP_DIR}/config/instance.env"
if [ -f "${INSTANCE_ENV}" ]; then
    # shellcheck disable=SC1090
    . "${INSTANCE_ENV}"
fi
if [ -z "${PROJECT_ID:-}" ]; then
    PROJECT_ID="$(curl -sf -H 'Metadata-Flavor: Google' \
        http://metadata.google.internal/computeMetadata/v1/project/project-id 2>/dev/null || true)"
fi
DASHBOARD_PORT="${DASHBOARD_PORT:-8000}"
PIPELINE_TIMEOUT="${PIPELINE_TIMEOUT:-20h}"

echo "==> Writing ${APP_DIR}/.env (generated — persistent edits go in config/instance.env)"
{
    echo "# GENERATED by scripts/vm_setup.sh — edits here are lost on re-run."
    echo "# Change config/instance.env instead, then re-run scripts/vm_setup.sh."
    # ADC must come from the metadata server (attached service account); a stale
    # GOOGLE_APPLICATION_CREDENTIALS pointing at a missing key file breaks it.
    grep -v '^GOOGLE_APPLICATION_CREDENTIALS=' "${APP_DIR}/.env.example"
    if [ -f "${INSTANCE_ENV}" ]; then
        echo ""
        echo "# --- from config/instance.env ---"
        cat "${INSTANCE_ENV}"
    fi
    echo ""
    echo "# --- computed by vm_setup.sh (last assignment wins) ---"
    echo "FOREST_SENTINEL_COG_ROOT=/data/cogs"
    if [ -n "${PROJECT_ID:-}" ]; then
        echo "FOREST_SENTINEL_GEE_PROJECT=${PROJECT_ID}"
        echo "FOREST_SENTINEL_GCS_STAGING_BUCKET=${STAGING_BUCKET:-${PROJECT_ID}-ofs-staging}"
    fi
    if [ -f "${APP_DIR}/config/aoi.geojson" ]; then
        echo "AOI_PATH=config/aoi.geojson"
    fi
} >"${APP_DIR}/.env"
if [ -z "${PROJECT_ID:-}" ]; then
    echo "warning: PROJECT_ID is not set in config/instance.env and the metadata" >&2
    echo "         server is unavailable — edit ${APP_DIR}/.env before running the pipeline." >&2
fi

echo "==> Starting PostgreSQL + PostGIS and applying migrations"
uv sync
# sudo: the docker-group membership granted above does not apply to the current
# login session, so plain `docker` would fail on the first (fresh-VM) run.
sudo docker compose up -d
for _ in $(seq 1 30); do
    sudo docker compose exec -T db pg_isready -U forest_sentinel >/dev/null 2>&1 && break
    sleep 2
done
set -a; . "${APP_DIR}/.env"; set +a
uv run alembic upgrade head

echo "==> Installing systemd units"
sed "s#@APP_DIR@#${APP_DIR}#g; s#@USER@#${USER}#g; s#@DASHBOARD_PORT@#${DASHBOARD_PORT}#g" \
    scripts/systemd/forest-sentinel-dashboard.service \
    | sudo tee /etc/systemd/system/forest-sentinel-dashboard.service >/dev/null
sed "s#@APP_DIR@#${APP_DIR}#g; s#@USER@#${USER}#g; s#@PIPELINE_TIMEOUT@#${PIPELINE_TIMEOUT}#g" \
    scripts/systemd/forest-sentinel-pipeline.service \
    | sudo tee /etc/systemd/system/forest-sentinel-pipeline.service >/dev/null
sudo cp scripts/systemd/forest-sentinel-pipeline.timer \
    /etc/systemd/system/forest-sentinel-pipeline.timer
sudo systemctl daemon-reload
sudo systemctl enable --now forest-sentinel-dashboard.service
sudo systemctl enable --now forest-sentinel-pipeline.timer
# Pick up the regenerated .env on re-runs (enable --now is a no-op when running).
sudo systemctl restart forest-sentinel-dashboard.service

if [ "${RUN_INITIAL}" = "1" ]; then
    echo "==> Triggering the initial pipeline run (async; watch journalctl)"
    sudo systemctl start forest-sentinel-pipeline.service --no-block
fi

cat <<EOF

On-VM setup complete.

  Settings live in config/instance.env (committed) — after changing it, re-run
  this script to regenerate .env and restart the dashboard.

  Dashboard:        systemctl status forest-sentinel-dashboard
  Scheduled run:    systemctl status forest-sentinel-pipeline.timer
  Trigger a run now: sudo systemctl start forest-sentinel-pipeline.service
  Logs:             journalctl -u forest-sentinel-pipeline -f
EOF
