"""SQLAlchemy domain models.

Each derived artifact in the system is traceable to its sources; the schema is
introduced incrementally, one bead at a time. This module currently defines the
``aoi`` table — the configured area of interest the rest of the pipeline runs
against.
"""

from datetime import datetime

from geoalchemy2 import Geometry
from geoalchemy2.elements import WKBElement
from sqlalchemy import DateTime, MetaData, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Areas of interest are stored in WGS 84 (EPSG:4326); loaders reproject on ingest.
AOI_SRID = 4326

# Deterministic constraint names keep hand-written and autogenerated migrations consistent.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all Open Forest Sentinel models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Aoi(Base):
    """A configured area of interest: the geometry the pipeline runs against."""

    __tablename__ = "aoi"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    geometry: Mapped[WKBElement] = mapped_column(
        Geometry(geometry_type="MULTIPOLYGON", srid=AOI_SRID),
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )
